apiVersion: v1
kind: Service
metadata: 
  name: microbot-deployment
  labels:
    app: microbot
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: microbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot-deployment
  labels:
    app: microbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbot
  template:
    metadata:
      labels:
        app: microbot
    spec:
      containers:
      - name: microbot
        image: dontrebootme/microbot:v1
        ports:
        - containerPort: 80
